from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC, wait
from selenium.webdriver.support.wait import WebDriverWait

options = webdriver.FirefoxOptions()
options.add_argument('start-maximized')
driver = webdriver.Firefox(options=options)
driver.get("https://demoqa.com/automation-practice-form")
driver.implicitly_wait(5)

first_name = WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.ID, 'firstName')))
first_name.send_keys('Alex_AQA')
last_name = driver.find_element(By.ID, 'lastName')
last_name.send_keys('Seniorovich')
email = driver.find_element(By.ID, 'userEmail')
email.send_keys('test@tut.by')
gender_radio_button = driver.find_element(By.XPATH, '//label[@for="gender-radio-1"]')
gender_radio_button.click()
mobile_number = driver.find_element(By.ID, 'userNumber')
mobile_number.send_keys('1234567890')
date_of_birth = driver.find_element(By.ID, 'dateOfBirthInput')
date_of_birth.click()
wait.WebDriverWait(driver, 5).until(EC.visibility_of_element_located((By.CLASS_NAME, 'react-datepicker__month')))
# date_of_birth.send_keys(Keys.CONTROL + "a")
# date_of_birth.send_keys('01012000')
# date_of_birth.send_keys(Keys.ENTER)
subjects = driver.find_element(By.ID, 'subjectsInput')
subjects.send_keys('English')
subjects.send_keys(Keys.ENTER)
hobbies = driver.find_element(By.XPATH, '//label[@for="hobbies-checkbox-1"]')
hobbies.click()
address = driver.find_element(By.ID, 'currentAddress')
address.send_keys('Baker str')
state = driver.find_element(By.ID, 'react-select-3-input')
state.send_keys('NCR')
state.send_keys(Keys.ENTER)
city = driver.find_element(By.ID, 'react-select-4-input')
city.send_keys('Delhi')
city.send_keys(Keys.ENTER)
submit_button = driver.find_element(By.ID, 'submit')
submit_button.click()
wait.WebDriverWait(driver, 5).until(EC.visibility_of_element_located(By.ID, 'example-modal-sizes-title-lg'))
driver.quit()
