from playwright.sync_api import Page, expect


def test_submit_form_with_playwright(page: Page):
    page.goto('https://demoqa.com/automation-practice-form')
    first_name = page.locator('#firstName')
    first_name.fill('Jonhy')
    last_name = page.locator('#lastName')
    last_name.fill('Silverhand')
    email = page.locator('#userEmail')
    email.fill('arasakatower@google.com')
    male = page.locator('//label[@for="gender-radio-1"]')
    male.click()
    phone = page.locator('#userNumber')
    phone.fill('1231231322')
    born_date = page.locator('#dateOfBirthInput')
    born_date.click()
    month = page.locator('//*[@class="react-datepicker__month-select"]')
    month.select_option('May')
    year = page.locator('//*[@class="react-datepicker__year-select"]')
    year.select_option('2000')
    day = page.locator('//div[@class="react-datepicker__day react-datepicker__day--019"]')
    day.click()
    subjects = page.locator('#subjectsInput')
    subjects.type('English')
    complete = page.locator('#react-select-2-option-0')
    complete.click()
    hobby = page.locator('//label[@for="hobbies-checkbox-3"]')
    hobby.click()
    address = page.locator('#currentAddress')
    address.fill('night city')
    state = page.locator('(//*[@class=" css-1hwfws3"])[1]')
    state.click()
    option_state = page.locator('#react-select-3-option-1')
    option_state.click()
    city = page.locator('(//*[@class=" css-1hwfws3"])[2]')
    city.click()
    option_city = page.locator('#react-select-4-option-2')
    option_city.click()
    submit = page.locator('#submit')
    submit.click()
    student_name = page.locator('//td[text()="Student Name"]/following-sibling::td')
    expect(student_name).to_have_text('Jonhy Silverhand')
