name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        type: choice
        description: select test to run
        required: true
        default: all
        options:
          - smoke
          - e2e
          - all
          

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: cd ui_tests_eokulik && pytest -v --alluredir=allure-results
      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: cd ui_tests_eokulik && pytest -v -m smoke --alluredir=allure-results
      - name: Run e2e tests
        if: "github.event.inputs.deployment_target == 'e2e'"
        run: |
          cd ui_tests_eokulik &&
          pytest -v -m e2e --alluredir=allure-results
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.30.0/allure-2.30.0.tgz && 
          sudo tar -zxvf allure-2.30.0.tgz -C /opt/ &&
          sudo ln -s /opt/allure-2.30.0/bin/allure /usr/bin/allure
      - name: Generate report
        run: allure generate -c ui_tests_eokulik/allure-results -o _site
      - name: save report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site
          retention-days: 2
        
      
  publish-report:
    name: Report publication
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
