name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        type: choice
        description: select test to run
        required: true
        default: all
        options:
          - smoke
          - e2e
          - all
          

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: cd ui_tests_eokulik && pytest -v
      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: cd ui_tests_eokulik && pytest -v -m smoke
      - name: Run e2e tests
        if: "github.event.inputs.deployment_target == 'e2e'"
        run: cd ui_tests_eokulik && pytest -v -m e2e
      
